/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sample_shop;

import static com.sun.corba.se.impl.orbutil.CorbaResourceUtil.getText;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.awt.event.*;
import java.sql.PreparedStatement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;


/**
 *
 * @author Shivi
 */
public class home1 extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    static int gtotal=0;
    static int tabletotal=0;
    static int sno=1;
    static int s_no=1;
    public home1() {
        initComponents();
        show_user();/*this function is used to display the items in the table 1*/
        date();
       total.setText("0");
       total.setEditable(false); 
    }
 public void removeTable1(){
    DefaultTableModel dm = (DefaultTableModel)table1.getModel();
    dm.getDataVector().removeAllElements();
    dm.fireTableDataChanged(); 
}
 public void removeTable2(){
    DefaultTableModel dm = (DefaultTableModel)table2.getModel();
    dm.getDataVector().removeAllElements();
    dm.fireTableDataChanged(); 
}
  
    public ArrayList<User>userList(){
    ArrayList<User>userList=new ArrayList<>();
     
    try {
		Class.forName("com.mysql.jdbc.Driver");
		Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?autoReconnect=true&useSSL=false", "root", "root");
		System.out.println("Connected");
                String query1="SELECT *from stock_detail";
                Statement st=conn.createStatement();
                 ResultSet rs=st.executeQuery(query1);
                 User user;
                 while(rs.next()){
                    user=new User(rs.getInt("sno"),rs.getString("pname"),rs.getInt("uprice"),rs.getInt("quantity"),rs.getInt("total"));
                    userList.add(user);
                         }
	conn.close();
	}catch(SQLException e){
             e.printStackTrace();
         }catch(Exception e1){
            System.out.println("error");
             e1.printStackTrace();
          }
    return userList;
    
    }
public void show_user(){
/*this fuction is displaying the values of database from the table and display in the table*/
ArrayList<User> list =userList();
DefaultTableModel model=(DefaultTableModel)table1.getModel();
Object[] row =new Object[6];
        int i;
for(i=0;i<list.size();i++){
    row[0]=sno++;
    row[1]=list.get(i).getpid();
    row[2]=list.get(i).getpname();
    row[3]=list.get(i).getquantity();
    row[4]=list.get(i).getuprice();
    row[5]=list.get(i).gettotal_amount();
    model.addRow(row);
}
}

public void date(){
/*thhis function is displaying the current date and display in the pdate field */

 LocalDate localdate=LocalDate.now();
        DateTimeFormatter f=DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String fs=localdate.format(f);
     pdate.setText(fs);
} 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoice = new javax.swing.JButton();
        stock = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        pdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        invoice_no = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JLabel();
        barcode = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        clearbutton = new javax.swing.JButton();
        get = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        remove = new javax.swing.JButton();
        print = new javax.swing.JButton();
        newbutton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        shortage = new javax.swing.JButton();
        expiry = new javax.swing.JButton();
        monthly = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        invoice.setText("Invoice");
        invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceActionPerformed(evt);
            }
        });
        getContentPane().add(invoice);
        invoice.setBounds(10, 20, 90, 23);

        stock.setText("Stock");
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        getContentPane().add(stock);
        stock.setBounds(10, 60, 90, 23);

        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setBackground(new java.awt.Color(0,168,117));

        jLabel1.setText("Purcahse Date");

        pdate.setEditable(false);
        pdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdateActionPerformed(evt);
            }
        });

        jLabel3.setText("Invoice No *");

        jLabel4.setText("Mobile No");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock Details"));

        search.setText("Barcode");

        barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeActionPerformed(evt);
            }
        });
        barcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barcodeKeyReleased(evt);
            }
        });

        addbutton.setText("ADD");
        addbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbuttonMouseClicked(evt);
            }
        });
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl.No.", "Pid", "Description", "Quantity", "Unit Price", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table1);

        clearbutton.setText("CLEAR");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        get.setText("GET PRODUCT");
        get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(31, 31, 31)
                        .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(get)
                        .addGap(18, 18, 18)
                        .addComponent(clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get)
                    .addComponent(clearbutton)
                    .addComponent(search))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addbutton)
                        .addGap(48, 48, 48))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Purchase Products"));

        remove.setText("REMOVE");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        newbutton.setText("NEW");
        newbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbuttonActionPerformed(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl. No.", "Pid", "Description", "Quantity", "Unit Price", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        table2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table2KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(table2);

        jLabel5.setText("GRAND TOTAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remove)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print))
                .addGap(18, 18, 18)
                .addComponent(newbutton)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(100, 100, 100)
                .addComponent(pdate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(invoice_no, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(invoice_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrame2);
        jInternalFrame2.setBounds(130, 30, 940, 580);

        shortage.setText("Shortage");
        shortage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortageActionPerformed(evt);
            }
        });
        getContentPane().add(shortage);
        shortage.setBounds(10, 100, 90, 23);

        expiry.setText("Expiry");
        expiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryActionPerformed(evt);
            }
        });
        getContentPane().add(expiry);
        expiry.setBounds(10, 140, 90, 23);

        monthly.setText("Report");
        monthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyActionPerformed(evt);
            }
        });
        getContentPane().add(monthly);
        monthly.setBounds(10, 180, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        stock stock_page=new stock(); 
        stock_page.dispose();
        expiry exp=new expiry();
         exp.dispose();
         monthly_reports m_r=new monthly_reports();
         m_r.dispose();
    }//GEN-LAST:event_invoiceActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
        stock stock_page=new stock();
        stock_page.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_stockActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void barcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcodeKeyReleased
        // TODO add your handling code here:
        /*this function is finding out the paricular product in the table from search field.
        but there is one problem that the last row is not deleting */
        /*this function search the particular item in the database and if not found then display a dialogue box "Not Found"
        and */
    /*  try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?autoReconnect=true&useSSL=false", "root", "root");

            Statement stmt=conn.createStatement();
            String temp=barcode.getText()+"%";
            ResultSet rs=stmt.executeQuery("select * from show_detail where pname like '"+temp+"'");
            rs.next();
            if(rs.getRow()==0)
            { //System.out.println("Not Found");
                JOptionPane.showMessageDialog(this, "Not Found");
            }
            else{
                DefaultTableModel model=(DefaultTableModel)table1.getModel();
                Object[] row=new Object[6];
                rs.previous();
                //if(model.getRowCount()!=0){
                    int i;
                    for(i=0;i<model.getRowCount();i++){
                        model.removeRow(i);
                    }
                    //}
                while(rs.next()){
                   
                    //Object[] obj={rs.getString("sno"),rs.getString("pname"),rs.getString("uprice"),rs.getString("quantity"),rs.getString("net_amount"),rs.getString("total_amount")};
                    //DefaultTableModel model=(DefaultTableModel)table1.getModel();
                   // model.addRow(obj);
                }
            }
           // System.out.println("Connected");

            conn.close();
        }catch(SQLException e){
            e.printStackTrace();
        }catch(Exception e1){
            System.out.println("error");
            e1.printStackTrace();
        }*/
    }//GEN-LAST:event_barcodeKeyReleased

    private void addbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbuttonMouseClicked
        // TODO add your handling code here:

        //System.out.println(s);
    }//GEN-LAST:event_addbuttonMouseClicked

   
    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed

        // TODO add your handling code here: poduct is adding to the table2 from table1.
        TableModel model1=table1.getModel();
        int index[] = table1.getSelectedRows();
        Object[] row=new Object[6];
        DefaultTableModel model2=(DefaultTableModel)table2.getModel();
        int length=table2.getRowCount();
        int pid=0;
       if(length==0){
        for(int i=0;i<index.length;i++)
            {
            row[1]=model1.getValueAt(index[i], 1);
            row[2]=model1.getValueAt(index[i], 2);
            row[3]=1;
            row[4]=model1.getValueAt(index[i], 4); 
            row[5]=(int)row[3]*(int)row[4];
            model2.addRow(row);        
            }
        }
        else{  
           int flag=1;
                for(int i=0;i<index.length;i++){     
                pid=(int)model1.getValueAt(index[i], 1);
                for(int j=0;j<length;j++){
                    int sno=(int)model2.getValueAt(j, 1);
                  if(pid==sno)
                  {
                  int no=(int)model2.getValueAt(j, 3);
                            no++;
                            model2.setValueAt(no, j, 3);
                           
                            int up=(int)model2.getValueAt(j, 4);
                            int t=up*no;
                            model2.setValueAt(t, j, 5);
                            flag=0;
                            break;
                  }
                  
               }
                if(flag==1)
                {
                row[1]=model1.getValueAt(index[i], 1);
                row[2]=model1.getValueAt(index[i], 2);
                row[3]=1;
                row[4]=model1.getValueAt(index[i], 4); 
                row[5]=(int)row[3]*(int)row[4];
                model2.addRow(row);
                }
                
               
                }
           
       } 
       /*error because of y=length if we remove then sno=1 is not printed correctly
       it will print after one iteration. if we don't remove then its working correctly but error is there.*/
       int s_no=1;
        for(int y=0 ;y<=length;y++){
            model2.setValueAt(s_no, y, 0); //setValueAt(data,row,column)
            s_no++;
        }
        //problem in gtotal while adding same product it doesnot change.
        gtotal=0;
        for(int j=0;j<table2.getRowCount();j++)
                     {
                         int t=(int)model2.getValueAt(j, 5);
                         System.out.println(t);
                         gtotal=gtotal+t;
                     total.setText(Integer.toString(gtotal));
                     }

        
    }//GEN-LAST:event_addbuttonActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table1MouseClicked

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        barcode.setText("");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here: product is removed from table2
        int s_no=1;
        TableModel model1=table2.getModel();
        int index[] = table2.getSelectedRows();
        DefaultTableModel model=(DefaultTableModel)table2.getModel();
        for(int i=0;i<index.length;i++){
            gtotal=gtotal-((int)model.getValueAt(index[i],4) *(int)model.getValueAt(index[i],3));
            total.setText(Integer.toString(gtotal));
            model.removeRow(index[i]);

        }
        int length=model.getRowCount();
        for(int y=0 ;y<length;y++){
            model.setValueAt(s_no, y, 0); //setValueAt(data,row,column)
            s_no++;
        }
        table2.revalidate();
        table2.repaint();
    }//GEN-LAST:event_removeActionPerformed

    private void newbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbuttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) table2.getModel();
        model.setRowCount(0);
        gtotal=0;
        total.setText(Integer.toString(gtotal));
    }//GEN-LAST:event_newbuttonActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table2MouseClicked

    private void table2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table2KeyReleased
        // TODO add your handling code here:
        TableModel model1=table2.getModel();
        Object[] row1=new Object[6];
        int index=table2.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)table2.getModel();
        int t=(int)model.getValueAt(index, 3) *(int)model.getValueAt(index, 4);
        model1.setValueAt(t ,index, 5);
        total.setText(Integer.toString(t));
        gtotal=gtotal+(int)model.getValueAt(index, 3);
        System.out.println(gtotal);
        /* this loop count the total value of column 4 and putted in grand total*/
        gtotal=0;
        for(int i=0;i<table2.getRowCount();i++)
        {   String d= table2.getValueAt(i, 4).toString();
            gtotal=gtotal+Integer.parseInt(d);
            total.setText(Integer.toString(gtotal));

        }
    }//GEN-LAST:event_table2KeyReleased

    private void barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodeActionPerformed

    private void pdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdateActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        TableModel model1=table2.getModel();
        TableModel model2=table1.getModel();
        Object[] row1=new Object[6];
        DefaultTableModel model=(DefaultTableModel)table2.getModel();
        DefaultTableModel model3=(DefaultTableModel)table1.getModel();
        int invoice=Integer.parseInt(invoice_no.getText());
        
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?autoReconnect=true&useSSL=false", "root", "root");
            Statement stmt=conn.createStatement();
            String date=pdate.getText();
            home1 frame=new home1();
        String message1="Are you sure you want to print";
        int ans=JOptionPane.showConfirmDialog(frame, message1);
         if(ans==JOptionPane.YES_OPTION){
            for(int i=0;i<table2.getRowCount();i++){
                int pid=(int)model1.getValueAt(i, 1);
                int quantity=(int)model1.getValueAt(i,3);
                int uprice=(int)model1.getValueAt(i,4);
                String query;
                query="insert into purchased values('"+invoice+"','"+pid+"','"+quantity+"','"+uprice+"','"+date+"')";
                
                PreparedStatement preparedStmt = conn.prepareStatement(query);
                preparedStmt.execute();
                 
                 invoice_no.setText("");
            }
            for(int i=0;i<table2.getRowCount();i++)
            {
                int pid=(int)model1.getValueAt(i, 1);
                 int quantity=(int)model1.getValueAt(i,3);
            int s_q=(int)model2.getValueAt(i,3)-quantity;
            String query1;
                query1="update stock_detail set quantity='"+s_q+"' where sno='"+pid+"'";
                PreparedStatement preparedStmt = conn.prepareStatement(query1);
                preparedStmt.executeUpdate();
            }
            removeTable2();
            removeTable1();
            show_user();
         }
            conn.close();
        }catch(Exception e){
            System.out.println("Error:");
        }
      
    }//GEN-LAST:event_printActionPerformed
    
    private void shortageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortageActionPerformed
        // TODO add your handling code here:
        shortage s_p=new shortage();
        s_p.setVisible(true);
        this.dispose();
       stock s=new stock();
       s.dispose();
        
    }//GEN-LAST:event_shortageActionPerformed

    private void getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getActionPerformed
        // TODO add your handling code here:
        
        try {
		Class.forName("com.mysql.jdbc.Driver");
		Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?autoReconnect=true&useSSL=false", "root", "root");
		System.out.println("Connected");
                String barCode=barcode.getText();
                if(barCode.equals(null) || barCode.equals(""))
                {
                JOptionPane.showMessageDialog(this, "Enter the Barcode");
                }
                String query1="SELECT *from stock_detail where sno='"+barCode+"'";
                Statement st=conn.createStatement();
                 ResultSet rs=st.executeQuery(query1);
                 if(rs.next()==true){
                DefaultTableModel model=(DefaultTableModel)table2.getModel();
                int sno=rs.getInt("sno");
                Object[] row =new Object[6];
                
                int length=table2.getRowCount();
                if(length==0){
                 int i=Integer.parseInt(barCode);
                     row[0]=s_no++;
                     row[1]=rs.getInt("sno");
                     row[2]=rs.getString("pname");
                     row[3]=1;
                     row[4]=rs.getInt("uprice");
                     row[5]=(int)row[3]*(int)row[4];
                    
                     model.addRow(row);
                    barcode.setText("");
                }
                else{
                    int flag=1;
                for(int j=0;j<length;j++)
                {
                     row[1]=model.getValueAt(j, 1);
                     
                     int pid=(int)row[1];
                     if(pid==sno){
                        int no=(int)model.getValueAt(j, 3);
                            no++;
                            model.setValueAt(no, j, 3);
                            row[3]=model.getValueAt(j, 3);
                            row[4]=model.getValueAt(j, 4);
                            int t=(int)row[3]*(int)row[4];
                            model.setValueAt(t, j, 5);
                              barcode.setText("");
                            flag=0;
                            break;
                     }
                     
                }
                     if(flag==1){
                     int i=Integer.parseInt(barCode);
                     row[0]=s_no++;
                     row[1]=rs.getInt("sno");
                     row[2]=rs.getString("pname");
                     row[3]=1;
                     row[4]=rs.getInt("uprice");
                     row[5]=(int)row[3]*(int)row[4];
                     model.addRow(row);                    
                    barcode.setText("");
                
                     }
                     
                }
                
	conn.close();}
                 else{
                 JOptionPane.showMessageDialog(this, "Enter the correct Barcode");
                 }
	}catch(SQLException e){
             e.printStackTrace();
         }catch(Exception e1){
            System.out.println("error");
             e1.printStackTrace();
          } 
        TableModel model=table2.getModel();
       gtotal=0;
        for(int j=0;j<table2.getRowCount();j++)
                     {
                         int t=(int)model.getValueAt(j, 5);
                         System.out.println(t);
                            gtotal=gtotal+t;
                     total.setText(Integer.toString(gtotal));
                     }
    }//GEN-LAST:event_getActionPerformed

    private void expiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryActionPerformed
        // TODO add your handling code here:
         this.dispose();
         expiry exp=new expiry();
         exp.setVisible(true);
        
    }//GEN-LAST:event_expiryActionPerformed

    private void monthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyActionPerformed
        // TODO add your handling code here:
        shortage s_p=new shortage();
         s_p.dispose();
         this.dispose();
         stock s=new stock();
         s.dispose();
         expiry exp=new expiry();
         exp.dispose();
         monthly_reports m_r=new monthly_reports();
         m_r.setVisible(true);
    }//GEN-LAST:event_monthlyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        home1 frame=new home1();
       // frame.setSize(1200,900);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JTextField barcode;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton expiry;
    private javax.swing.JButton get;
    private javax.swing.JButton invoice;
    private javax.swing.JTextField invoice_no;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton monthly;
    private javax.swing.JButton newbutton;
    private javax.swing.JTextField pdate;
    private javax.swing.JButton print;
    private javax.swing.JButton remove;
    private javax.swing.JLabel search;
    private javax.swing.JButton shortage;
    private javax.swing.JButton stock;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
