/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sample_shop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static sample_shop.shortage.sno;

/**
 *
 * @author Shivi
 */
public class monthly_reports extends javax.swing.JFrame {

    /**
     * Creates new form monthly_reports
     */
    public monthly_reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_button = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        e_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        s_date = new javax.swing.JTextField();
        e_date = new javax.swing.JTextField();
        get_report = new javax.swing.JButton();
        sale_button = new javax.swing.JRadioButton();
        purchase_button = new javax.swing.JRadioButton();
        invoice = new javax.swing.JButton();
        stock = new javax.swing.JButton();
        shortage = new javax.swing.JButton();
        expiry = new javax.swing.JButton();
        monthly = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setBackground(new java.awt.Color(0,168,117));

        e_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sno", "Product Name", "Quantity", "Unit Price", "Purchasing Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(e_table);

        jLabel1.setText("Start Date");

        jLabel2.setText("End Date");

        //s_date.setEditable(false);
        s_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_dateActionPerformed(evt);
            }
        });

        get_report.setText("GET REPORT");
        get_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_reportActionPerformed(evt);
            }
        });

        group_button.add(sale_button);
        sale_button.setText("Sold Products");
        sale_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sale_buttonActionPerformed(evt);
            }
        });

        group_button.add(purchase_button);
        purchase_button.setText("Purchased Products");
        purchase_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGap(0, 102, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(sale_button)
                                .addGap(51, 51, 51)
                                .addComponent(purchase_button)
                                .addGap(89, 89, 89)
                                .addComponent(get_report, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(s_date, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(e_date, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(e_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sale_button)
                    .addComponent(purchase_button)
                    .addComponent(get_report))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        invoice.setText("Invoice");
        invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceActionPerformed(evt);
            }
        });

        stock.setText("Stock");
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });

        shortage.setText("Shortage");
        shortage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortageActionPerformed(evt);
            }
        });

        expiry.setText("Expiry");
        expiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryActionPerformed(evt);
            }
        });

        monthly.setText("Monthly Report");
        monthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shortage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiry, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthly))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(invoice)
                        .addGap(18, 18, 18)
                        .addComponent(stock)
                        .addGap(18, 18, 18)
                        .addComponent(shortage)
                        .addGap(18, 18, 18)
                        .addComponent(expiry)
                        .addGap(18, 18, 18)
                        .addComponent(monthly))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public ArrayList<monthly_products>productList(){
    ArrayList<monthly_products>productList=new ArrayList<>();
     
    try {
		Class.forName("com.mysql.jdbc.Driver");
		Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?autoReconnect=true&useSSL=false", "root", "root");
		System.out.println("Connected");
                String sdate=s_date.getText();
                String edate=e_date.getText();
                Statement st;
                ResultSet rs=null;
                if(sale_button.isSelected()==true){
                    String query1="select s.pname,p.quantity,p.uprice,p.pdate from stock_detail s,purchased p where p.pdate>='"+sdate+"'and p.pdate<='"+edate+"' and p.pid=s.sno";
                    st=conn.createStatement();
                    rs=st.executeQuery(query1);
                    monthly_products month_product;
                    String d;
                    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                    while(rs.next()){
                        d=sdf.format(rs.getDate("pdate"));
                        month_product=new monthly_products(rs.getString("pname"),rs.getInt("quantity"),rs.getInt("uprice"),d);
                        productList.add(month_product);
                    }
                }else if(purchase_button.isSelected()==true){
                    String query1="select pname,quantity,uprice,pdate from stock_detail where pdate>='"+sdate+"'and pdate<='"+edate+"'";
                    st=conn.createStatement();
                    rs=st.executeQuery(query1);
                    monthly_products month_product;
                    String d;
                    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                    while(rs.next()){
                        d=sdf.format(rs.getDate("pdate"));
                        month_product=new monthly_products(rs.getString("pname"),rs.getInt("quantity"),rs.getInt("uprice"),d);
                        productList.add(month_product);
                    }
                    
                    /*
                        Add purchased date in stock_detail table.
                        And then edit this part.
                        Ensure that adding new column doesn't affect the functionality of adding stock.
                    */
                }else{
                    JOptionPane.showMessageDialog(this, "select one option");
                }
                conn.close();
	}catch(SQLException e){
             e.printStackTrace();
         }catch(Exception e1){
            System.out.println("error");
             e1.printStackTrace();
          }
    return productList;
    
     }
public void show_product(){


/*this fuction is displaying the values of database from the table and display in the table*/
ArrayList<monthly_products> list =productList();
DefaultTableModel model=(DefaultTableModel)e_table.getModel();
Object[] row =new Object[5];
        int i;
for(i=0;i<list.size();i++){
    row[0]=sno++;
    row[1]=list.get(i).getpname();
    row[2]=list.get(i).getuprice();
    row[3]=list.get(i).getquantity();
    row[4]=list.get(i).getdate();
    model.addRow(row);
}
}
    
 public void removeTable(){
DefaultTableModel dm = (DefaultTableModel)e_table.getModel();
dm.getDataVector().removeAllElements();
dm.fireTableDataChanged(); 
}
    private void invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceActionPerformed
        // TODO add your handling code here:
        home1 home=new home1();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_invoiceActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
        stock s=new stock();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stockActionPerformed

    private void shortageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortageActionPerformed
        // TODO add your handling code here:
        this.dispose();
        shortage s=new shortage();
        s.setVisible(true);
    }//GEN-LAST:event_shortageActionPerformed

    private void expiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryActionPerformed
        // TODO add your handling code here:
        expiry exp=new expiry();
        exp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_expiryActionPerformed

    private void monthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        home1 home=new home1();
        home.dispose();
        stock s=new stock();
        s.dispose();
        shortage ss=new shortage();
        ss.dispose();
        expiry exp=new expiry();
        exp.dispose();
      
    }//GEN-LAST:event_monthlyActionPerformed

    private void purchase_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchase_buttonActionPerformed

    private void sale_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sale_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sale_buttonActionPerformed

    private void get_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_reportActionPerformed
        // TODO add your handling code here
        if(sale_button.isSelected()==true)
        {
            removeTable();
            show_product();
        }else if(purchase_button.isSelected()==true){
            removeTable();
            show_product();
        }else{
            JOptionPane.showMessageDialog(this,"Select one option");
        }
        /*  if(purchase_button.isSelected()==true)
        {
            ResultSet rs= stmt.executeQuery("select * from stock_detail where exp_date>='"+sdate+"'and exp_date<='"+edate+"'");
            while(rs.next()){
                System.out.println(rs.getInt("sno"));
            }*/
    }//GEN-LAST:event_get_reportActionPerformed

    private void s_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_dateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(monthly_reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(monthly_reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(monthly_reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(monthly_reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new monthly_reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField e_date;
    private javax.swing.JTable e_table;
    private javax.swing.JButton expiry;
    private javax.swing.JButton get_report;
    private javax.swing.ButtonGroup group_button;
    private javax.swing.JButton invoice;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton monthly;
    private javax.swing.JRadioButton purchase_button;
    private javax.swing.JTextField s_date;
    private javax.swing.JRadioButton sale_button;
    private javax.swing.JButton shortage;
    private javax.swing.JButton stock;
    // End of variables declaration//GEN-END:variables
}
